### ISSUE TITLE
9anime.ru 

### ISSUE THREAD

**Issue by nyabingi59** [SuperMarcus/NineAnimator#112]
Not working

**Comment by SuperMarcus** [comment]
Hi there. I will mark this issue as invalid because we don't have enough information to diagnose the error you're getting. Please open another issue with the [Bug Report](https://github.com/SuperMarcus/NineAnimator/issues/new/choose) template if you intend to report a problem. To help us better diagnose your issue, please fill in as much information as you can in the template.

We've had a lot of issues with 9anime in the past, and most of them have been resolved. Please use the [issue tracker](https://github.com/SuperMarcus/NineAnimator/issues) to look for existing issues as well.

If you have more questions, feel free to join our Discord server at https://discord.gg/dzTVzeW.
