### ISSUE TITLE
[BUG] Replace with Description

### ISSUE THREAD

**Issue by dearfox4578** [SuperMarcus/NineAnimator#114]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: [e.g. iPhone Xs Max]
 - OS: [e.g. iOS 13.3]
 - Version: [e.g. v1.2-3 or commit hash]

**Crash Log**
```
If applicable, paste the crash log inside this block.
(Goto Settings.app -> Privacy -> Analytics & Improvements -> Analytics Data to find crash logs)
```

**Additional context**

**Comment by SuperMarcus** [comment]
Hi there. I will mark this issue as invalid because we don't have enough information to diagnose the error you're getting. Please open another issue with the [Bug Report](https://github.com/SuperMarcus/NineAnimator/issues/new/choose) template if you intend to report a problem. To help us better diagnose your issue, please fill in as much information as you can in the template.

If you have more questions, feel free to join our Discord server at https://discord.gg/dzTVzeW.
