### ISSUE TITLE
Help please.

### ISSUE THREAD

**Issue by chae112** [SuperMarcus/NineAnimator#115]
![080F7301-5AC0-4488-9AF7-89511FEA9326](https://user-images.githubusercontent.com/64654624/80823774-8bc4e400-8c20-11ea-91d9-30630752c3bb.png)
How should I fix this?

**Comment by uttiya10** [comment]
From the two issues that you have created, I'm guessing that you have downloaded this app from the App Store. Unfortunately, this version of the app is very outdated and has many bugs. Please download the TestFlight version. You can get instructions on our discord: https://discord.gg/DmaT8S

P.S. Do not create MULTIPLE ISSUES! And please FILL OUT THE FORM that we have provided, otherwise we can't provide the help you need. Next time, we will mark your issue as invalid and simply close your issue. Thank you!
