### ISSUE TITLE
Nineanimator error 

### ISSUE THREAD

**Issue by killia504** [SuperMarcus/NineAnimator#119]
Hi I am a big fan of the app and I wanted to let you guys know about this. When I try to view the episodes it will come up with a error with the servers. I hope you guys can take care of this for me. 

Thanks

**Comment by uttiya10** [comment]
Please either join our discord at https://discord.gg/BxXqUx and we will help you there, or you can create another issue on github and FILL OUT THE FORM that we have provided!! Otherwise it is IMPOSSIBLE to help you with your problem! Next time, we will simply label your issue as invalid and close it.

**Comment by SuperMarcus** [comment]
Hi there. First and foremost, we're glad that you enjoy using the app. In order to help us pinpoint the issue, please tell us more about the error you're getting by editing your issue and with the following template. You can edit your issue by tapping on the `...` button and tap Edit.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Device (please complete the following information):**
 - Device: [e.g. iPhone Xs Max]
 - OS: [e.g. iOS 13.3]
 - Version: [e.g. v1.2-3 or commit hash]

**Crash Log**
```
If applicable, paste the crash log inside this block.
(Goto Settings.app -> Privacy -> Analytics & Improvements -> Analytics Data to find crash logs)
```

**Additional context**
Add any other context about the problem here.
