### ISSUE TITLE
[BUG] 4anime URLError: There is something wrong with the url.

### ISSUE THREAD

**Issue by matthefoo** [SuperMarcus/NineAnimator#122]
It keeps tell me to Verified And it not let me watch
![E731D745-9AFC-4DD7-A780-4700B54EF363](https://user-images.githubusercontent.com/64812492/81619717-120ac400-939f-11ea-9c32-99777b699bbd.png)

**Comment by uttiya10** [comment]
@matthefoo Please either join our discord at https://discord.gg/BxXqUx and we will help you there, or you can create another issue on github and FILL OUT THE FORM that we have provided!! Otherwise it is IMPOSSIBLE to help you with your problem! Next time, we will simply label your issue as invalid and close it.

**Comment by Catta1997** [comment]
@matthefoo
> It keeps tell me to Verified And it not let me watch

I have tried to play episode 1 of Naruto Shippuden on 4anime and it works. do you have the App Store version or the TestFlight version? Also the error does not say you to verify but it says that there is a problem with the url

**Comment by SuperMarcus** [comment]
Thank you for reporting this issue.

It looks like you're using the App Store version of NineAnimator. The current app store version is outdated. For now, we're only keeping the Github version and the TestFlight version update to date.

For more information, please join our Discord server with the link @uttiya10 posted above.
