### ISSUE TITLE
9anime doesn’t work

### ISSUE THREAD

**Issue by DoobiYT** [SuperMarcus/NineAnimator#126]
Everything I try to click on an anime it tells me that there is an error.

**Comment by uttiya10** [comment]
@DoobiYT Please either join our discord at https://discord.gg/rp6NAyX and we will help you there, or you can create another issue on github and FILL OUT THE FORM that we have provided!! Otherwise it is IMPOSSIBLE to help you with your problem! Next time, we will simply label your issue as invalid and close it.

**Comment by Catta1997** [comment]
AppStore or TestFlight version?

**Comment by SuperMarcus** [comment]
The information you have provided is not sufficient for us to diagnose this issue. However, most of the issues regarding 9anime should have been fixed in the repository. Try looking for existing issues in the [issue tracker](https://github.com/SuperMarcus/NineAnimator/issues?q=is%3Aissue) to see if any of them matches the one you're getting.
