### ISSUE TITLE
Can I upload your app on App Store after editing features ?

### ISSUE THREAD

**Issue by KrLikeblue** [SuperMarcus/NineAnimator#161]
Hello Marcus, 

Your code is awesome and you are really genius. Now I want to edit your app and want to upload on App Store. Would that be possible ?

And all the anime sources you have used are free one or copyrighted ? I mean can apple reject this app because of copyright issue ?

Thanks
Patel

**Comment by SuperMarcus** [comment]
Thank you for your comments. I'm not sure if I deserve to be called a "genius," but I can certainly answer some of your questions.

> I want to edit your app and want to upload on App Store.

We don't want people to upload our app to the App Store, modified or not. This is because we already have a version of NineAnimator on the App Store, and Apple has been rejecting our updates because of 4.3 Design - Spam: "we noticed that your app provides the same feature set as other apps submitted to the App Store."

Having multiple submissions of our code significantly impacts our ability to pass the App Store reviews, and we sincerely hope that people are not taking our code and submitting it to the App Store. If you don't know this already, there exist multiple clones of our app on the App Store, some of them charge people hundreds of dollars for what's supposed to be freely available to everyone.

> ...all the anime sources you have used are free one or copyrighted?

All of the sources implemented in the app are publicly available and free to use. The app is simply a ”browser” that presents the information from each source in an organized manner.

> ...can apple reject this app because of copyright issue(s)?

Apple can reject an app if they suspect violations of copyright laws. I'm not an attorney, so I cannot speak of the legal aspects of NineAnimator.

I'll be closing this issue for now, but let me know if you have more questions. If you're not in our Discord server, feel free to join with this link: [https://discord.gg/dzTVzeW](https://discord.gg/dzTVzeW).
