### ISSUE TITLE
[Feature Request] Trakt support

### ISSUE THREAD

**Issue by Dankakot05** [SuperMarcus/NineAnimator#182]
A way of syncing episodes that have been watched to a trakt account in addition to the anime traking lists

**Comment by SuperMarcus** [comment]
Trakt doesn't seem to be a very popular service in our community and among other anime communities (?), so implementing this tracking service will not be our priority concern for the time being. We do have someone bringing this up in our Discord server. So I'm curious what are the advantages of this service compared to the other trackers (Anilist, MAL, Kitsu, Simkl) that are already implemented in the app?

I'll be closing this issue now because we are not planning to implement Trakt support anytime soon. But feel free to respond under this issue. If you are not already in our Discord community, feel free to join with this link: https://discord.gg/dzTVzeW
