### ISSUE TITLE
UNABLE TO USE 9anime SOURCE ON MAC

### ISSUE THREAD

**Issue by animudatte** [SuperMarcus/NineAnimator#185]
i cant use the 9anime source and it is the only one which i support the most as the quality is the best so pls fixx it

**Comment by SuperMarcus** [comment]
I'm marking this issue as invalid because we can't find the necessary information to diagnose the problem. Please use the issue template when drafting new issues.

Also, we are aware that there are some problems related to the 9anime source. The 9anime website redesigned their website recently. As a result, some of the code in our repository needs to be updated to reflect their changes.
