### ISSUE TITLE
[BUG] Replace with Description

### ISSUE THREAD

**Issue by aljaari** [SuperMarcus/NineAnimator#254]
**STOP!!** Before submitting this bug report, make sure you have filled out the information below and renamed the title of this issue (ex. `[BUG] UrlError when trying to stream an episode on 9ani.app`). The information you provide helps us diagnose the problem and organize our issue tracker.

**Describe the bug**
Replace this line with a clear and concise description of what the bug is.

**To Reproduce**
Replace this with the steps to reproduce the behavior:

**Expected behavior**
Replace this line with a clear and concise description of what you expected to happen.

**Screenshots**

**Device:**
Replace the following with the device on which you're experiencing this issue.
 - Device: [e.g. iPhone Xs Max]
 - OS: [e.g. iOS 13.3]
 - Version: [e.g. v1.2-3 or commit hash]

**Crash Log**
```
If applicable, paste the crash log inside this block.
(Goto Settings.app -> Privacy -> Analytics & Improvements -> Analytics Data to find crash logs)
```

**Additional context**

**Comment by uttiya10** [comment]
Hi there. I will mark this issue as invalid because we don't have enough information to diagnose the error you're getting. Please open another issue with the Bug Report template if you intend to report a problem. To help us better diagnose your issue, please fill in as much information as you can in the template.

If you have more questions, feel free to join our Discord server at https://discord.gg/dzTVzeW.
