### ISSUE TITLE
[BUG] Not able to add notifications for NineAnimator in Mac

### ISSUE THREAD

**Issue by DanielFerrariR** [SuperMarcus/NineAnimator#255]
![Screen Shot 2021-05-13 at 12 36 00 PM](https://user-images.githubusercontent.com/18249831/118149469-f5f19680-b3e7-11eb-9aa3-f525b3e499e8.png)

In the Macbook version of the app, even if the app telling me to enable notifications, I can't see the app in system preferences > notifications.

**Comment by uttiya10** [comment]
Thanks for the bug report! I suspect this is caused because we currently do not code-sign the macOS application, which could prevent NineAnimator from asking for permission.

If you have Xcode installed, can you try running this commands to sign the app yourself and see if notifications work? If not, I can provide a signed version myself later.

Open the terminal and run this command:
`codesign --force --deep --sign - /Applications/NineAnimator.app`

**Comment by DanielFerrariR** [comment]
Tried to sign it, but because of alt store, I don't have any id app ids left, maybe that's why it didn't work. if someone else can try to sign it and check if it appears in the notification panel, it didn't work for me.

**Comment by uttiya10** [comment]
I have attached a version of NineAnimator that was signed using ad-hoc signing. I was able to get Notification permissions using this signed version of the app on my machine. Please try it, and report if it fixes the issue.

[NineAnimatorSigned.zip](https://github.com/SuperMarcus/NineAnimator/files/6475597/NineAnimatorSigned.zip)

**Comment by DanielFerrariR** [comment]
Yeah, it shows the notifications now.

**Comment by uttiya10** [comment]
Glad to hear that signing the app has fixed the issue. I'll try to update the build script soon to sign the macOS application for future versions.

**Comment by ISnackable** [comment]
Closing as resolved in #315
