### ISSUE TITLE
[BUG] Artwork does not load for Hanime source

### ISSUE THREAD

**Issue by Swishiie** [SuperMarcus/NineAnimator#260]
Hanime artworks aren't showing at all, just shows a blank 9.

**Comment by Arch-0** [comment]
It's a known problem, it won't be fixed until NACore is finished.

**Comment by Swishiie** [comment]
Ah, will both of these things be in the next update?

**Comment by Arch-0** [comment]
it will probably take a while since it's a big internal change. But more than likely, yes.

**Comment by Swishiie** [comment]
ah okay, thanks!

**Comment by uttiya10** [comment]
Re-opening issue since it has not been fixed yet

**Comment by uttiya10** [comment]
Sorry for the very late reply!
A bunch of the code base has been going through a internal restructuring, which is why it's taken some time for the sources to be fixed.

Here is where you can download the beta version of NineAnimator, which should have the source fixed:
https://github.com/SuperMarcus/NineAnimator/actions/runs/992458342

**Comment by Awsomedude** [comment]
The issue has been fixed.
