### ISSUE TITLE
[BUG] (iPadOS 15) Pantsubase just stopped working one day

### ISSUE THREAD

**Issue by Joseos123** [SuperMarcus/NineAnimator#262]
**Describe the bug**

nothing is able to be streamed, this applies to ALL anime, i have tried at least 10 different titles.

![image](https://user-images.githubusercontent.com/59199097/122680621-b4dc7580-d222-11eb-9d52-731630b8d404.png)

unable to download anything either as it just stays at 0% forever

context: i watched the entire season of this on pantsubase both downloaded and streamed and a few days later i couldnt stream anything from pantsubase

**Device:**
 - Device: iPad Pro 11" 1st gen (2018)[A1980]
 - OS: iPadOS 15.0 Developer Beta (19A5261w)
 - Version: d88b431

**Crash Log**
N/A

**Comment by Layendan** [comment]
Pantsubase is currently broken on the latest version. If you used AltStore to download the app, you can use this nightly update: <https://nightly.link/uttiya10/NineAnimator/workflows/nightly/fix-pantsubase/NineAnimator_Nightly.0adb6afa.iOS.zip> to have the Pantsubase fix. Watching anime using that source should be fixed with that update.

Note: this is a nightly and hence might not be stable, please make a backup of your settings and history before updating the app.

**Comment by Joseos123** [comment]
uhh in the version number it clearly says im using the latest commit. not sure if the nightly build is AHEAD of the latest commit but, i used xcode 13 to get it on as im on ios 15

**Comment by Joseos123** [comment]
as i dont use altstore because it seems to not work on ios 15, please provide the commit hash that i should use, or is it in a different branch other than master?

**Comment by Joseos123** [comment]
fixed with latest pr
