### ISSUE TITLE
[Feature Request] Add AnimeWorld Support

### ISSUE THREAD

**Issue by Raffa2001** [SuperMarcus/NineAnimator#69]
Hi i would like if you add this italian server https://www.animeworld.tv/ who host ita sub and dub, and i can help with the traslation, i done a sketch
![photo6034833224938664320](https://user-images.githubusercontent.com/62517834/77257711-6387b400-6c76-11ea-841d-021962dddd5f.jpg)

**Comment by SuperMarcus** [comment]
As I've responded in the old subreddit thread, I'd love to implement another international source to the app. However, since I'm not very good at Italian I might misinterpret some parts of the website.

Also, we're currently working on implementing Anime Unity, another Italian anime source, into the app. See #68 and #40.

**Comment by Catta1997** [comment]
I can add that too, it's not very different from AnimeUnity so I have to edit only the parsing. If for @SuperMarcus is ok I can add the support on the same pull request

**Comment by Raffa2001** [comment]
> I can add that too, it's not very different from AnimeUnity so I have to edit only the parsing. If for @SuperMarcus is ok I can add the support on the same pull request

It will be even better if he make a way to add your own servers

**Comment by Catta1997** [comment]
---ITA---
comunque in locale l'ho creato e funziona. Riguardo alla possibilità di aggiungere i server non è semplice, bisogna fare il parsing dei siti web per trovare i link e l'unico modo è modificare il progetto dell'applicazione
---ENG---
however locally I created it and it works. As for the ability to add the servers yourself is not easy, you need to analyze the websites to find the links and use them. the only way is to edit the project

**Comment by SuperMarcus** [comment]
It appears that AnimeWorld is also not region blocked. It may be a good alternative for Italian audiences living in other parts of the world. Would you mind working on this as well @Catta1997?

Looks like this website is structured similarly to 9anime. So implementations [here](https://github.com/SuperMarcus/NineAnimator/tree/master/NineAnimator/Models/Anime%20Source/9anime.to) may serve as a template.

**Comment by Raffa2001** [comment]
> It appears that AnimeWorld is also not region blocked. It may be a good alternative for Italian audiences living in other parts of the world. Would you mind working on this as well @Catta1997?
> 
> 
> 
> Looks like this website is structured similarly to 9anime. So implementations [here](https://github.com/SuperMarcus/NineAnimator/tree/master/NineAnimator/Models/Anime%20Source/9anime.to) may serve as a template.

Yeah dude, he have the same structure of the design and pages

**Comment by Catta1997** [comment]
@SuperMarcus, JSON search appears to have some limitations. In fact if you search for "Conan" instead of "Detective Conan" the search returns an empty JSON (also with Postman) , I think that the json is made by "suggested" search. Also JSON will return only 5 element instead 25 (for example with Detective Conan)

**Comment by Catta1997** [comment]
For AnimeWorld I'll do the pull request today

**Comment by SuperMarcus** [comment]
> JSON search appears to have some limitations...

Noted. I guess I'll have to revert those changes. I rewrote part of the old search agent because there was a spin loop in the `more()` method.

https://github.com/SuperMarcus/NineAnimator/blob/dd281dbbf837d6e49f29e903baad04b9cc98d0ea/NineAnimator/Models/Anime%20Source/animeunity.it/AnimeUnity%2BSearch.swift#L47-L48

`more()` may be called from the main thread, so we don’t want that.

**Comment by Raffa2001** [comment]
> > JSON search appears to have some limitations...
> 
> Noted. I guess I'll have to revert those changes. I rewrote part of the old search agent because there was a spin loop in the `more()` method.
> 
> https://github.com/SuperMarcus/NineAnimator/blob/dd281dbbf837d6e49f29e903baad04b9cc98d0ea/NineAnimator/Models/Anime%20Source/animeunity.it/AnimeUnity%2BSearch.swift#L47-L48
> 
> `more()` may be called from the main thread, so we don’t want that.

I will try to contact the founders to help you with the code so it will be easier

**Comment by Raffa2001** [comment]
> > JSON search appears to have some limitations...
> 
> Noted. I guess I'll have to revert those changes. I rewrote part of the old search agent because there was a spin loop in the `more()` method.
> 
> https://github.com/SuperMarcus/NineAnimator/blob/dd281dbbf837d6e49f29e903baad04b9cc98d0ea/NineAnimator/Models/Anime%20Source/animeunity.it/AnimeUnity%2BSearch.swift#L47-L48
> 
> `more()` may be called from the main thread, so we don’t want that.

btw i think you wrinte in the wrong session, this is the animeworld.tv, and you put a link to the animeunity.it code

**Comment by SuperMarcus** [comment]
@Raffa2001 you are absolutely correct. This should have been posted in #68's discussions. I was just responding to Catta1997's comment.

**Comment by DanielVip3** [comment]
Hi! I'm the (new) developer of AnimeWorld.tv.

We'd like to ask you to not add our site within your app's sources, to avoid load from webscraping and requests (also, our owner's a bit mad 'bout others using our things, y'know).
Please keep in mind webscraping is illegal, and we have all the copyright on our code source, so please, we ask you to not webscrape on our site.
Also, we don't earn nothing about this webscraping, because our ads are not in the player, and we're just losing bandwidth from our own servers to serve all this people which doesn't even know our site and never comes over it. We most likely are only losing from this.

For @Raffa2001: we're also minding to make an app in the near future, with our APIs, so there's no need of this right now. Cioè, e poi se non ti sta bene fatti una webview del sito e veditela tu (che poi P.S. abbiamo una webview su Aptoide) in attesa della nostra app.

Thanks to all the developer community of this open-source project and thanks for trying to add AnimeWorld, we like your work and keep going with other sources.

**Comment by SuperMarcus** [comment]
Since the representative of AnimeWorld has spoken, I will be closing this issue now.
