### ISSUE TITLE
[BUG] 9ani.app links do not open in NineAnimator

### ISSUE THREAD

**Issue by uttiya10** [SuperMarcus/NineAnimator#76]
When opening a 9ani.app link safari, this is what appears:
![BCF24012-48D9-4B47-8E6E-9B62F89CE85D](https://user-images.githubusercontent.com/56562649/77814404-214fdf80-7087-11ea-9786-9196099cd58c.png)

When clicking “View”, it simply redirects you to the anime website, instead of opening NineAnimator.

**Comment by uttiya10** [comment]
Ok this seems to be a problem with Discord, and not with your website. When clicking a 9ani.app link in Discord, discord simply opens it in the in-app-browser, instead of in NineAnimator. However, when I emailed myself the link, and opened it using the Gmail app, Gmail had opened NineAnimator instead of it's in-app-browser. So clearly its a problem with Discord.

**Comment by SuperMarcus** [comment]
Yes, it may be related to how discord handles universal links. Because of some fuzzy internal logics, tapping the View button in Safari also won't redirect you to the app. You still have to scroll down on the page to open the link in the app. For now, I'm just going to add a small note under the share page.

**Comment by uttiya10** [comment]
Just wanted to let you know, that scrolling down to show the open button, doesn’t work in discord! Ill keep the issue closed.
