### ISSUE TITLE
[Feature Request] Add AnimeSaturn

### ISSUE THREAD

**Issue by iFelix18** [SuperMarcus/NineAnimator#91]
Please, add [AnimeSaturn](https://www.animesaturn.com/), a well-stocked Italian anime site.

**Comment by uttiya10** [comment]
Italian websites load so fast compared to english websites. Kinda jealous.

**Comment by Catta1997** [comment]
I can try. Anyway in the meantime there is AnimeUnity that is an Italian server

**Comment by Catta1997** [comment]
@iFelix18 nel sito esiste una ricerca o devi selezionare l'anime nella lista di "autocompletamento"? se premo "invio" la pagina si ricarica. è un errore momentaneo o devo premere su "Naruto"?
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/34333654/78644038-87bdd480-78b5-11ea-9134-49b2112d44a0.png">

**Comment by iFelix18** [comment]
Non esiste una pagina con i risultati mostrati graficamente, bisogna premere su "Naruto" da l'autocompletamento, il quale prende i dati da:
https://www.animesaturn.com/index.php?search=1&key=naruto

```JSON
[
  {
    "name":"Naruto",
    "link":"Naruto",
    "image":"https:\/\/cdn.animesaturn.com\/static\/images\/locandine\/17405l.jpg",
    "release":"03 Ottobre 2002",
    "state":"1"
  },
  {
    "name":"Naruto (ITA)",
    "link":"Naruto-ITA",
    "image":"https:\/\/cdn.animesaturn.com\/static\/images\/locandine\/17405l.jpg",
    "release":"03 Ottobre 2002",
    "state":"1"
  },
  {
    "name":"Naruto Shippuden",
    "link":"Naruto-Shippuden",
    "image":"https:\/\/cdn.animesaturn.com\/static\/images\/locandine\/17407l.jpg",
    "release":"15 Febbraio 2007",
    "state":"1"
  },
  {
    "name":"Naruto Shippuden (ITA)",
    "link":"Naruto-Shippuden-ITA",
    "image":"https:\/\/cdn.animesaturn.com\/static\/images\/locandine\/17407l.jpg",
    "release":"15 Febbraio 2007",
    "state":"1"
  },
  {
    "name":"Boruto: Naruto the Movie",
    "link":"Boruto-Naruto-the-Movie-a",
    "image":"https:\/\/cdn.animesaturn.com\/static\/images\/locandine\/78280l.jpg",
    "release":"07 Agosto 2015",
    "state":"1"
  }
]
```

**Comment by Catta1997** [comment]
ok comincio a lavorarci

**Comment by Catta1997** [comment]
I'm having trouble doing the "Search" function, I'm having a problem requesting a JSON with alamofire. I also have problems analyzing it and then returning the values. @SuperMarcus  can you help? also it is the only step that I'm not able to do

**Comment by uttiya10** [comment]
@Catta1997 Looks like you can do a get request to `https://www.animesaturn.com/loading_anime?anime_id=` in order to get list of episodes, You will need to send the get request with `x-requested-with` header with a value of `XMLHttpRequest`, otherwise you will get an error.

You can import this into Postman if you want to play around:
https://pastebin.com/B35fA2q5

To get the anime ID of any anime, you can check the page source:
There is a div tag: `<div class="container p-3 shadow rounded bg-dark-as-box">`
In the div tag, there is a meta tag with a `content` attribute. The value of it, is the anime ID.

**Comment by Catta1997** [comment]
> @Catta1997 Looks like you can do a get request to `https://www.animesaturn.com/loading_anime?anime_id=` in order to get list of episodes, You will need to send the get request with `x-requested-with` header with a value of `XMLHttpRequest`, otherwise you will get an error.
> 
> You can import this into Postman if you want to play around:
> https://pastebin.com/B35fA2q5
> 
> To get the anime ID of any anime, you can check the page source:
> There is a div tag: `<div class="container p-3 shadow rounded bg-dark-as-box">`
> In the div tag, there is a meta tag with a `content` attribute. The value of it, is the anime ID.

great, I only have to found a way to inspect a page before to inspect another to get the list of the episodes

**Comment by SuperMarcus** [comment]
@Catta1997 My apologies for not seeing the discussions that's been going on with this issue.

To simulate an XHR request, use the `request(ajax)` methods in `BaseSession`. Those methods make requests with the `retrieveSession`, which includes the necessary configurations that mimic the behaviors of an XHR request.

Please let me know if there's anything I can help with.

**Comment by Catta1997** [comment]
> @Catta1997 My apologies for not seeing the discussions that's been going on with this issue.
> 
> To simulate an XHR request, use the `request(ajax)` methods in `BaseSession`. Those methods make requests with the `retrieveSession`, which includes the necessary configurations that mimic the behaviors of an XHR request.
> 
> Please let me know if there's anything I can help with.

No problem. I have tried ` request(ajaxUrlString: link.link)` but I have the same problem as `request(browseUrl: link.link)` the given parsing is "incorrect", because the website has a "loading" before give the buttons of the episodes. And both give me the page with the "loading" instead of the page with the buttons.

**Comment by Catta1997** [comment]
@iFelix18 sei ancora interessato?

**Comment by iFelix18** [comment]
@Catta1997 Se fattibile si, certo.

**Comment by Catta1997** [comment]
ok, only have one problem, to get the link to the video I have to do two requests because when I click on the episode button does not appear the video but a page with a link to the page vith the video, I have to understand how to do it. I have done all the other things
______
ok, ho solo un problema, per ottenere il link al video devo fare due richieste perché quando faccio clic sul pulsante "episodio" non appare il video ma una pagina con un link alla pagina con il video, devo capire come farlo. Ho fatto tutte le altre cose

**Comment by Catta1997** [comment]
#166

**Comment by Awsomedude** [comment]
Closing since AnimeSaturn has been added.
